#!/bin/bash

# command line snippets
# @author github.com/dmerc (dmerc.net)

# source snipp_completion for bash completion

# --------- FUNCTIONS
usage(){
  echo -n "$(basename $0) [OPTIONS] ACTION SNIPPET
Manage text snippets.

 Actions:
  e|edit            Edit the specified snippet, using \$EDITOR
  s|show            Show the specified snippet
  ls|list           List all snippets
  rm|remove         Remove a snippet
 Options:
  -p, --print       Show snippet without a pager
  -h, --help        Display this help and exit
  -v, --version     Output version information and exit
      --nocolor     Disable color
      --nowarn      Disable warnings
      --printpath   Prints the snippet file's path, and exits. Only for show action.

 Examples:
  snipp show bash # shows snippet on bash
  snipp edit cpp  # opens cpp snippet in \$EDITOR
  snipp html      # shows snippet on html
"
}
require_arguments(){
  if [[ $# -lt 2 ]]; then
    echo '** not enough arguments **'
    exit 0
  fi
}
err(){
  >&2 echo "$1"
}
warn(){
  if [[ $WARNINGS == 1 ]]; then
    echo "$1"
  fi
}

SNIPP_DEFAULT_BASEDIR=~/.snipp/
# CONFIG
if [[ ! -z "$SNIPP_BASEDIR" ]]; then
  if [[ ! -d "$SNIPP_BASEDIR" ]]; then
    err 'snipp base directory is set but the path is not a directory'
    err 'aborting.'
    exit 1
  else
    SNIPP_BASEDIR=$SNIPP_DEFAULT_BASEDIR
  fi
else
  SNIPP_BASEDIR=$SNIPP_DEFAULT_BASEDIR
fi

VERSION="0.2"
PRINTER="less -r "

# disable color when piped
[[ -t 1 ]] && COLORED=1 || COLORED=0
WARNINGS=1
ONLYPRINTSNIPPPATH=0

if [ ! -d $SNIPP_BASEDIR ]; then
  mkdir -p $SNIPP_BASEDIR
fi

# ACTIONS
action_edit(){
  snippet_path=$SNIPP_BASEDIR$1
  $EDITOR $snippet_path
}
action_list(){
  ls $SNIPP_BASEDIR
}
action_delete(){
  snippet_path=$SNIPP_BASEDIR$1
  if [ -f $snippet_path ]; then
    rm -i $snippet_path
  else
    warn "** Snippet '$1' does not exist **"
    exit 1
  fi
}
action_show(){
  snippet_path=$SNIPP_BASEDIR$1

  if [ $ONLYPRINTSNIPPPATH == 1 ]; then
    echo $snippet_path
    exit 0
  fi

  if [ -f $snippet_path ]; then

    TMP=/tmp/snipp

    if [ $COLORED == 1 ]; then
      show_colored $snippet_path
    else
      filter_snipp_meta
      $PRINTER $TMP
    fi
  else
    warn "** Snippet '$1' does not exist **"
    exit 1
  fi
}
filter_snipp_meta(){
    # delete first line if it contains 'syntax:'
    cat $snippet_path | sed '1,2{;/syntax:.*/d;}' > $TMP
    # then delete first line if blank
    sed '1{/^$/d}' $TMP
}
show_colored(){
  if hash pygmentize 2>/dev/null; then
    detect_pygments_lexer $1
    if [ -n "$_OPT" ]; then
      filter_snipp_meta
      pygmentize $_OPT $TMP | $PRINTER
    else
      warn "cant detect syntax for highlighting, use a file extension"
      warn "or add the string 'syntax:something' to the head of this snippet"
      filter_snipp_meta
      $PRINTER $TMP
    fi
  else
    warn "install 'pygments' for snippet syntax highlighting"
    filter_snipp_meta
    $PRINTER $TMP
  fi
}
detect_pygments_lexer(){
  _OPT=""
  if [ -z "${1//[^.]/}" ]; then
    # has an extension. delegate detection to pygments.
    return
  else
    # try to find "syntax:something" in the head of the file
    lexer=$(head -n 2 $1 | grep -oE "syntax:.*([[:space:]]|$)" | head -n 1; echo "x")
    # this preserves newlines from the subshell
    lexer="${lexer%x}"
    # cutout <lexer> from the "... syntax:<lexer> ...." line
    lexer=${lexer#*syntax:}
    lexer=${lexer% *}
    if [ -n "$lexer" ]; then
      _OPT="-l $lexer"
    else
      _OPT=""
    fi
  fi
}


# --------- PARSE INPUT/OPTIONS

[[ $# -eq 0 ]] && set -- "--help"

# Read the options and set stuff
while [[ $1 = -?* ]]; do
  case $1 in
    -h|--help) usage >&2; exit 0 ;;
    -v|--version) echo "$(basename $0) $VERSION"; exit 0 ;;
    -p|--print) PRINTER=cat ;;
    --nocolor) COLORED=0 ;;
    --nowarn) WARNINGS=0 ;;
    --printpath) ONLYPRINTSNIPPPATH=1 ;;
    --endopts) shift; break ;;
    *) warn "** Invalid option '$1' **"; exit 1 ;;
  esac
  shift
done
case $1 in
  s|show)
    require_arguments $@;
    SNIPPET=`echo -e ${2//\//_}`
    action_show $SNIPPET
  ;;
  e|edit)
    require_arguments $@;
    SNIPPET=`echo -e ${2//\//_}`
    action_edit $SNIPPET
  ;;
  ls|list)
    action_list
  ;;
  rm|remove)
    require_arguments $@;
    SNIPPET=`echo -e ${2//\//_}`
    action_delete $SNIPPET
  ;;
  *)
    action_show $1
  ;;
esac
